### ISSUE TITLE
Can't run textdistance

### ISSUE THREAD

**Issue by ArneBachmann** [orsinium/textdistance#1]
Both Python 2.7.14 64bit and 2.7.7 32 bit
```Python
>>> import textdistance
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python27\lib\site-packages\textdistance\__init__.py", line 109
      def w(f, *texts, equality=False):
                            ^
SyntaxError: invalid syntax
>>>
```

**Comment by ArneBachmann** [comment]
My workaround after testing several libraries looks as follows:
```Python
try:
  from textdistance import distance as _distance  # https://github.com/orsinium/textdistance
  def distance(a, b): return _distance('l', a, b)  # h = hamming, l = levenshtein, dl = damerau-levenshtein
  assert distance("abc", "cbe") == 2  # until bug has been fixed
  if verbose: print("Using textdistance library")
except:
  try:
    from edit_distance import SequenceMatcher as _distance # ttps://github.com/belambert/edit-distance
    def distance(a, b): return _distance(a, b).distance()
    assert distance("abc", "cbe") == 2
    if verbose: print("Using edit_distance library")
  except:
    try:
      from editdistance import eval as distance  # https://pypi.python.org/pypi/editdistance/0.2
      assert distance("abc", "cbe") == 2
      if verbose: print("Using editdistance library")
    except:
      def distance(a, b): return 0 if a == b else 1  # simple distance measure fallback
      assert distance("abc", "cbe") == 1
      if verbose: print("Using simple comparison")
```

**Comment by orsinium** [comment]
textdistance developed for python3, sorry. I think, this error related with combination of starred notation and keyword arguments.
You can use python3, remove `equality` argument from your own code or make fork & pull request for compatibility with python2.

**Comment by ArneBachmann** [comment]
OK, will give it a shot at making it portable.

**Comment by orsinium** [comment]
GNU license allow you improve and contribute this module. Feel free to contribute :)

**Comment by orsinium** [comment]
@ArneBachmann, now TextDistance big, fast and popular. Thank you for help on start :)
