### ISSUE TITLE
Tanimoto TypeError: 'super' object is not callable

### ISSUE THREAD

**Issue by QwertyCoolMT** [orsinium/textdistance#29]
Traceback (most recent call last):
  File "file.py", line 119, in <module>
    hungarian(dict1.keys(),dict2.keys())
  File "file.py", line 100, in hungarian
    row.append(getattr(textdistance, algo).distance(i.lower(), j.lower()))
  File "/home/pc/miniconda3/lib/python3.7/site-packages/textdistance/algorithms/base.py", line 164, in distance
    return self.maximum(*sequences) - self.similarity(*sequences)
  File "/home/pc/miniconda3/lib/python3.7/site-packages/textdistance/algorithms/base.py", line 167, in similarity
    return self(*sequences)
  File "/home/pc/miniconda3/lib/python3.7/site-packages/textdistance/algorithms/token_based.py", line 188, in __call__
    result = super(Tanimoto, self)(*sequences)
TypeError: 'super' object is not callable

**Comment by orsinium** [comment]
Please, provide steps to reproduce.

**Comment by mavroprovato** [comment]
Steps to reproduce:

$ python --version
Python 3.6.7

```
>>> import textdistance
>>> print(textdistance.__version__)
3.0.2
>>> textdistance.tanimoto.normalized_similarity('hello', 'hallo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxxx/Code/Python/test/venv/lib/python3.6/site-packages/textdistance/algorithms/base.py", line 49, in normalized_similarity
    return 1 - self.normalized_distance(*sequences)
  File "/home/xxxxx/Code/Python/test/venv/lib/python3.6/site-packages/textdistance/algorithms/base.py", line 42, in normalized_distance
    return float(self.distance(*sequences)) / self.maximum(*sequences)
  File "/home/xxxxx/Code/Python/test/venv/lib/python3.6/site-packages/textdistance/algorithms/base.py", line 164, in distance
    return self.maximum(*sequences) - self.similarity(*sequences)
  File "/home/xxxxx/Code/Python/test/venv/lib/python3.6/site-packages/textdistance/algorithms/base.py", line 167, in similarity
    return self(*sequences)
  File "/home/xxxxx/Code/Python/test/venv/lib/python3.6/site-packages/textdistance/algorithms/token_based.py", line 188, in __call__
    result = super(Tanimoto, self)(*sequences)
TypeError: 'super' object is not callable
```
